version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 16
  build:
    commands:
      - echo Building the Go code...
      - make build
      - echo Building the Node code...
artifacts:
  secondary-artifacts:
    golang_artifacts:
      files:
        - gitea
